### ISSUE TITLE
[開発]Trpg用Solrツールの開発

### ISSUE THREAD

**Issue by SomaPrime** [SomaPrime/TrpgTool#6]
# チケットの説明

# TODO
- [ ] #1 [開発]Solrを立てる
- [ ] #2 [開発][調査]Solrの調査
- [ ] #3 [開発][検討]Solrの定義を決める
- [ ] #4 [開発][検討]Solrツールに使う技術を検討
- [ ] #5 [開発][作成]Solrツールの作成
